### ISSUE TITLE
File browser not displaying files

### ISSUE THREAD

**Issue by Backfighter** [mruby-zest/mruby-zest-build#28]
When trying to save my instruments the file browser does not list any files. 
When opening the file browser (doesn't matter if save, load) the following error is displayed in the terminal and on of the threads segvaults:
```
Unknown address<BACKEND:online> '/file_list_dirs:'
Unknown path '/file_list_dirs:'
Unknown address<BACKEND:online> '/file_list_files:'
Unknown path '/file_list_files:'
Unknown address<BACKEND:online> '/file_list_dirs:'
Unknown path '/file_list_dirs:'
Unknown address<BACKEND:online> '/file_list_files:'
Unknown path '/file_list_files:'
```
This issue doesn't seem to be new since I could find the following two reports with a similar issue:
https://www.kvraudio.com/forum/viewtopic.php?t=498341
https://sourceforge.net/p/zynaddsubfx/bugs/168/

According to the posts the issue has been fixed in 3.0.3, but I'm currently using 3.0.5:
```
$ zynaddsubfx --version

ZynAddSubFX - Copyright (c) 2002-2013 Nasca Octavian Paul and others
                Copyright (c) 2009-2019 Mark McCurry [active maintainer]
This program is free software (GNU GPL v2 or later) and 
it comes with ABSOLUTELY NO WARRANTY.

Version: 3.0.5
```
Could this be a regression?

I would like to attach a screenshot and the coredump, but currently github won't let me upload files for some reason.

**Comment by fundamental** [comment]
This issue comes up from time to time, but it's not something that I've been able to replicate (so far). It's unclear to me if there is a precondition in the operating system, some system encoding, characters in file paths, etc. The Unknown address issues is harmless and not directly related to the crash, though it is something which should be resolved at some point.

Getting a backtrace for the crash would be useful though, so if you can obtain that, it would be great.

**Comment by Backfighter** [comment]
Here the stack trace. I'm still unable to upload the coredump. I might look into other file sharing facilities.
```
Stack trace of thread 1989:
#0  0x00007f3cd58034b5 __strlen_avx2 (libc.so.6 + 0x1624b5)
#1  0x0000558b8ce8daa2 rtosc_amessage (zynaddsubfx + 0x15f>
#2  0x0000558b8cdbf4c9 _ZN3zyn9MwDataObj10replyArrayEPKcS2>
#3  0x0000558b8cdb7cfb n/a (zynaddsubfx + 0x89cfb)
#4  0x0000558b8ce835b0 _ZNK5rtosc5Ports8dispatchEPKcRNS_6R>
#5  0x0000558b8cdb4ae6 _ZN3zyn14MiddleWareImpl9handleMsgEP>
#6  0x0000558b8cdb59cd n/a (zynaddsubfx + 0x879cd)
#7  0x00007f3cd5e4ce49 n/a (liblo.so.7 + 0x8e49)
#8  0x00007f3cd5e4ef31 n/a (liblo.so.7 + 0xaf31)
#9  0x00007f3cd5e4f2ae lo_server_recv (liblo.so.7 + 0xb2ae)
#10 0x00007f3cd5e4f53e lo_servers_recv_noblock (liblo.so.7>
#11 0x00007f3cd5e4f5a0 lo_server_recv_noblock (liblo.so.7 >
#12 0x0000558b8cdb51af _ZN3zyn10MiddleWare4tickEv (zynadds>
#13 0x0000558b8cd783f4 main (zynaddsubfx + 0x4a3f4)
#14 0x00007f3cd56c8002 __libc_start_main (libc.so.6 + 0x27>
#15 0x0000558b8cd86ffe _start (zynaddsubfx + 0x58ffe)

Stack trace of thread 1992:
#0  0x00007f3cd5768571 clock_nanosleep@@GLIBC_2.17 (libc.s>
#1  0x00007f3cd576de87 __nanosleep (libc.so.6 + 0xcce87)
#2  0x00007f3cd5798d99 usleep (libc.so.6 + 0xf7d99)
#3  0x0000558b8ce7f480 _ZN3zyn9NulEngine11AudioThreadEv (z>
#4  0x00007f3cd5e83422 start_thread (libpthread.so.0 + 0x9>
#5  0x00007f3cd57a0bf3 __clone (libc.so.6 + 0xffbf3)
```

**Comment by fundamental** [comment]
So, I'm not great with using core dump files, but looking at the backtrace the crash would appear to have happened at one of:
- https://github.com/fundamental/rtosc/blob/master/src/rtosc.c#L182
- https://github.com/fundamental/rtosc/blob/master/src/rtosc.c#L184
- https://github.com/fundamental/rtosc/blob/master/src/rtosc.c#L218

The third being most likely.
That's getting called from https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/Misc/MiddleWare.cpp#L842 which if you're using the file browser is likely getting called from one of:

- https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/Misc/MiddleWare.cpp#L1382
- https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/Misc/MiddleWare.cpp#L1401

I can't see anything in those blocks which would result in an invalid argument destination path or invalid argument type string, so that leaves some string (representing a file path) which either is somehow an invalid pointer stored through a std::string object or an invalidly terminated string. With either case the strings which are eventually passed to strlen are from https://github.com/zynaddsubfx/zynaddsubfx/blob/07b4f0230336c9657285c812f279cc8a8561183e/src/Misc/MiddleWare.cpp#L930 .

I can't see anything in that block which would cause the issue, nor do I see any notes in the man page of readdir() which would imply that there should be an expectation that the field might contain invalid data.

So... yeah, I don't know what's causing the issue, but the readdir code region is likely causing it.

**Comment by Backfighter** [comment]
That's unfortunate. I can reproduce the issue on all of my machines (Arch linux). Is there a way to save instruments without the file explorer?

**Comment by Backfighter** [comment]
So I discovered something very weird. Basically I just added some print statements just to see what's happening with the values and the print statements actually fixed the issue:
```
diff --git a/src/Misc/MiddleWare.cpp b/src/Misc/MiddleWare.cpp
index 49bce2ca..59481162 100644
--- a/src/Misc/MiddleWare.cpp
+++ b/src/Misc/MiddleWare.cpp
@@ -1367,6 +1369,7 @@ static rtosc::Ports middwareSnoopPorts = {
         types[N] = 0;
         for(int i=0; i<N; ++i) {
             args[i].s = files[i].c_str();
+            std::cout << "Received:" << args[i].s << "\n";
             types[i]  = 's';
         }
 
@@ -1386,6 +1389,7 @@ static rtosc::Ports middwareSnoopPorts = {
         types[N] = 0;
         for(int i=0; i<N; ++i) {
             args[i].s = files[i].c_str();
+            std::cout << "Receivedd:" << args[i].s << "\n";
             types[i]  = 's';
         }


```
I tried this multiple times and it worked every time. There is definitely something very fishy going on here. I'm not very deep into the C/C++ world, but maybe this has something to do with the optimizations gcc 10 does? Do you have any idea how this could happen?

**Comment by fundamental** [comment]
I've thought about this one for a while, since I think I recall seeing
something similar early on in the development cycle.
Printing is going to change codegen slightly and it will change the
timing of when messages are sent out.
I can't think of any reason why different codegen would change the
overall behavior (usually this happens when there's undefined or
implementation defined behavior involved).
The problem is it's not clear to my why changing the timing ought to fix
things either.
Either way, something about adding that print on your system results in
either different messages, differently ordered messages, or messages
spaced in time differently.

I'm guessing this is enough of a complex issue that you'd want to have
the prints on the zynaddsubfx side and on the receiving osc-bridge
side.
Specifically mruby-zest-build/src/osc-bridge/src/bridge.c:202..280

**Comment by Backfighter** [comment]
https://github.com/zynaddsubfx/zynaddsubfx/commit/22a5f8da76c16c47c3814eedaec8f9fe0ff4248b
Seems to have fixed the issue for me.
